require("prototypes.builder_avatar")
require("prototypes.builder_inventory_armor")
require("prototypes.clanker_artillery")
require("prototypes.enemy_builder_research")
require("prototypes.fixed_recipe_assemblers")
